// Code Generated by Sidekick is for learning and experimentation purposes only.
import React from 'react';
import { Card, Row, Col } from "react-bootstrap";
import ProductList from '../products/ProductList';
import Title from '../categorieslist/Title';
const Cattemplate = ({ cats = [], products = [] }) => {
  return (
    <Row>
      
      {cats.map((cat, index) => (
        
        <Col key={index}>
           
          <Card>
            <Title/>
            <ProductList products={products} />
            
          </Card>
        </Col>
       
      ))}
    </Row>
  
  );
};

export default Cattemplate;
