// Code Generated by Sidekick is for learning and experimentation purposes only.
import React from 'react';
import ImpNav from './Nav';
import ProductList from './products/ProductList';
import { lehengaProducts } from './products/Allproducts';


const Lehenga=()=>(
  <div>
    <ImpNav/>
    <h1>Lehenga</h1>
    <ProductList products={lehengaProducts}/>
  </div>
)

export default Lehenga;
