// Code Generated by Sidekick is for learning and experimentation purposes only.
import React from 'react';
import ImpNav from './Nav';
import ProductList from './products/ProductList';
import { regionalProducts } from './products/Allproducts';


const Regional=()=>(
  <div>
    <ImpNav/>
    <h1>Regional</h1>
    <ProductList products={regionalProducts}/>
  </div>
)

export default Regional;
