// Code Generated by Sidekick is for learning and experimentation purposes only.

import React from 'react';
import { Routes, Route } from 'react-router-dom';
import ImpNav from './component/Nav';
import './App.css';
import Index from './component/Index';
import Silk from './component/categorieslist/Silk';
import Cotton from './component/categorieslist/Cotton';
import Lehenga from './component/categorieslist/Lehenga';
import Salwar from './component/categorieslist/Salwar';
import Regional from './component/categorieslist/Regional';
import { AuthProvider } from './component/categorieslist/AuthContext';
import Login from './component/categorieslist/Login';
import { CartProvider } from './component/categorieslist/CartContext';
import CartModal from './component/categorieslist/CartModal';
import Cart from './component/categorieslist/Cart';
import Footer from './component/Footer'

function App() {
  return (
    <AuthProvider>
     
      <CartProvider>
        <ImpNav />
        <CartModal />
        <Routes>
          <Route path='/' element={<Index />} />
          <Route path='/Silk' element={<Silk />} />
          <Route path='/Cotton' element={<Cotton />} />
          <Route path='/Lehenga' element={<Lehenga />} />
          <Route path='/Salwar' element={<Salwar />} />
          <Route path='/Regional' element={<Regional />} />
          <Route path='/login' element={<Login />} />
          <Route path='/cart' element={<Cart />} />
        </Routes>
      </CartProvider>
      <Footer/>
    </AuthProvider>
  );
}

export default App;
